---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html

- name: Assert not to run on anything other than Python 3
  ansible.builtin.assert:
    that:
      - ansible_python.version.major == 3
    quiet: true

- name: Test if netbox_stable_version is set
  ansible.builtin.assert:
    that:
      - netbox_stable_version is defined
    quiet: false
