---


- name: "Set os_family dependent variables"
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: "Set distribution dependent variables"
  ansible.builtin.include_vars: "{{ item }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      paths:
        - 'vars'
      skip: true
  loop: "{{ query('first_found', params, errors='ignore') }}"
