---
# prepare test host with things not included in the role you are testing

- name: Prepare
  hosts: all
  become: true
  roles:
    - { role: geerlingguy.postgresql }
    - { role: geerlingguy.redis }
    - { role: geerlingguy.nginx }
