---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html
# Ansible is declaritive so don't test everything - just test the desired outcome of the role
#
- name: Verify
  hosts: all
  tasks:
    - name: Verify something
      ansible.builtin.debug:
        msg: "This is the verify step you wish you had"

# example of validating the desired outcome
#
#    - name: Test if https is accepting requests
#      ansible.builtin.uri:
#        url: https://localhost/
#        status_code: 200
#        validate_certs: false
#      register: this
#    - name: validate we get redirected to a login page
#      assert:
#        that:
#          - "'https://localhost/login/?next=/' is in this.url"
